package automod_legacy

// These words are listed in in alphabethical order.
var BuiltinSwearWords = map[string]bool{
	"anal":        true,
	"anus":        true,
	"arse":        true,
	"ass":         false,
	"b1tch":       false,
	"ballsack":    false,
	"bastard":     true,
	"bitch":       false,
	"biatch":      false,
	"blowjob":     true,
	"bollock":     true,
	"bollok":      true,
	"boner":       true,
	"boob":        false,
	"boobs":       false,
	"buttplug":    true,
	"clitoris":    true,
	"cock":        true,
	"cum":         true,
	"cunt":        true,
	"dick":        false,
	"dildo":       true,
	"dyke":        true,
	"erection":    true,
	"fag":         true,
	"faggot":      true,
	"feck":        true,
	"fellate":     true,
	"fellatio":    true,
	"felching":    true,
	"fuck":        false,
	"fucks":       false,
	"fudgepacker": true,
	"genitals":    false,
	"hell":        false,
	"jerk":        false,
	"jizz":        true,
	"knobend":     true,
	"labia":       true,
	"masturbate":  true,
	"muff":        true,
	"nigger":      true,
	"nigga":       true,
	"penis":       false,
	"piss":        false,
	"poop":        false,
	"pube":        false,
	"pussy":       false,
	"scrotum":     false,
	"sex":         true,
	"shit":        false,
	"sh1t":        false,
	"slut":        true,
	"smegma":      true,
	"spunk":       true,
	"tit":         true,
	"tranny":      true,
	"trannies":    true,
	"tosser":      true,
	"turd":        false,
	"twat":        true,
	"vagina":      true,
	"wank":        true,
	"whore":       true,
	"tits":        true,
	"titty":       true,
	"asshole":     false,
	"fvck":        true,
	"asshat":      false,
	"pu55y":       true,
	"pen1s":       true,
    "coon":        true,
"Carpet Muncher": true,
    "ape":        true,
	"rape":       true,
	"Retard":     true,
    "retarded":   true,
	"Chink":      true,
	"beaner":     true,
	"Spic":       true,
	"spik":       true,
	"spick":      true,
"spear chucker":  true,
	






	
